### ISSUE TITLE
Windows 8.1 VS 2013 - problem?

### ISSUE THREAD

**Issue by dazinator** [AshleyGrant/aspnet-skeleton-navigation#5]
After following the instructions, when I build the solution for the first time, I get the following build error:

```
Error	6	The build tools for Visual Studio 2010 (Platform Toolset = 'v100') cannot be found. To build using the v100 build tools, please install Visual Studio 2010 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Upgrade Solution...". [G:\Users\Darrell\Source\Repos\aspnet-skeleton-navigation\aspnet-skeleton-navigation\node_modules\karma\node_modules\socket.io\node_modules\socket.io-client\node_modules\ws\build\validation.vcxproj]	aspnet-skeleton-navigation
```

The message doesn't make that much sense, as right clicking on the solution within VS - there is no "Upgrade" option.

I think this might be a node-gyp issue but not sure: https://github.com/TooTallNate/node-gyp/issues/421#issuecomment-49251267

**Comment by dazinator** [comment]
This seems like it could be pertinant, but would this mean I would need to change one of the msbuild scripts (targets, props) somewhere:-

```@pablovianini I solved by installing Node.js packages with --msvs-version=2013 command switch.

For example:

npm install protractor --msvs-version=2013
```

**Comment by AshleyGrant** [comment]
I don't currently have VS2013 set up on my laptop. Could you try changing this line: https://github.com/AshleyGrant/aspnet-skeleton-navigation/blob/master/build/MSBuild.Npm.props#L5 to add in the switch you mentioned and delete your npm_packages folder and see if that fixes it?

**Comment by dazinator** [comment]
Adding the additional switch fixed it, without clearing packages directory. The app now runs!

I did a quick google, and there should be an msbuild property you can use to check the VS version if that helps: http://stackoverflow.com/questions/11935426/detect-visual-studio-version-from-within-msbuild-project

Thanks for your help :)

**Comment by dazinator** [comment]
I think changing the contents of `msbuild.npm.props` to something like this would fix it - let me know if you'd prefer a PR:
```
 <PropertyGroup Condition="'$(VisualStudioVersion)' == '12.0'">
    <NpmFile>$(MSBuildProjectDirectory)\package.json</NpmFile>
    <NpmCommand>install --loglevel error --msvs-version=2013</NpmCommand>
  </PropertyGroup>

  <PropertyGroup Condition="'$(VisualStudioVersion)' != '12.0'">
    <NpmFile>$(MSBuildProjectDirectory)\package.json</NpmFile>
    <NpmCommand>install --loglevel error</NpmCommand>
  </PropertyGroup>
```
